// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: jwt.proto

package com.seezoon.jwt.stub;


/**
* Validates {@code SignResp} protobuf objects.
*/
@SuppressWarnings("all")
public class SignRespValidator implements io.envoyproxy.pgv.ValidatorImpl<com.seezoon.jwt.stub.SignResp>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(com.seezoon.jwt.stub.SignResp.class)) return new SignRespValidator();
		
		return null;
	}
		
	
	
	

	public void assertValid(com.seezoon.jwt.stub.SignResp proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	// no validation rules for Token

	
	
	}

}

