// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: jwt.proto

package com.seezoon.jwt.stub;


/**
* Validates {@code SignReq} protobuf objects.
*/
@SuppressWarnings("all")
public class SignReqValidator implements io.envoyproxy.pgv.ValidatorImpl<com.seezoon.jwt.stub.SignReq>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(com.seezoon.jwt.stub.SignReq.class)) return new SignReqValidator();
		
		return null;
	}
		
	
	
	

	public void assertValid(com.seezoon.jwt.stub.SignReq proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
		if (proto.hasJwtInfo()) {
			io.envoyproxy.pgv.RequiredValidation.required(".com.seezoon.jwt.SignReq.jwtInfo", proto.getJwtInfo());
		} else {
			io.envoyproxy.pgv.RequiredValidation.required(".com.seezoon.jwt.SignReq.jwtInfo", null);
		};
			// Validate jwtInfo
			if (proto.hasJwtInfo()) index.validatorFor(proto.getJwtInfo()).assertValid(proto.getJwtInfo());
	
	
	}

}

