// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jwt.proto

// Protobuf Java Version: 3.25.3
package com.seezoon.jwt.stub;

public interface SignReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.seezoon.jwt.SignReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.seezoon.jwt.JwtInfo jwtInfo = 1 [(.validate.rules) = { ... }</code>
   * @return Whether the jwtInfo field is set.
   */
  boolean hasJwtInfo();
  /**
   * <code>.com.seezoon.jwt.JwtInfo jwtInfo = 1 [(.validate.rules) = { ... }</code>
   * @return The jwtInfo.
   */
  com.seezoon.jwt.stub.JwtInfo getJwtInfo();
  /**
   * <code>.com.seezoon.jwt.JwtInfo jwtInfo = 1 [(.validate.rules) = { ... }</code>
   */
  com.seezoon.jwt.stub.JwtInfoOrBuilder getJwtInfoOrBuilder();
}
