// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: jwt.proto

package com.seezoon.jwt.stub;


/**
* Validates {@code VerifyResp} protobuf objects.
*/
@SuppressWarnings("all")
public class VerifyRespValidator implements io.envoyproxy.pgv.ValidatorImpl<com.seezoon.jwt.stub.VerifyResp>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(com.seezoon.jwt.stub.VerifyResp.class)) return new VerifyRespValidator();
		
		return null;
	}
		
	
		
	
	
	

	public void assertValid(com.seezoon.jwt.stub.VerifyResp proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	// no validation rules for Valid

	
			// Validate jwtInfo
			if (proto.hasJwtInfo()) index.validatorFor(proto.getJwtInfo()).assertValid(proto.getJwtInfo());
	
	
	}

}

