// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: jwt.proto

package com.seezoon.jwt.stub;


/**
* Validates {@code VerifyReq} protobuf objects.
*/
@SuppressWarnings("all")
public class VerifyReqValidator implements io.envoyproxy.pgv.ValidatorImpl<com.seezoon.jwt.stub.VerifyReq>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(com.seezoon.jwt.stub.VerifyReq.class)) return new VerifyReqValidator();
		
		return null;
	}
		
	
	
	

	public void assertValid(com.seezoon.jwt.stub.VerifyReq proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
			io.envoyproxy.pgv.StringValidation.minLength(".com.seezoon.jwt.VerifyReq.token", proto.getToken(), 20);
	
	
	}

}

